
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cottonheart-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=asia-southeast1-001.proxy.kinsta.app
      - DB_PORT=30339
      - DB_NAME=bare-magenta-magpie
      - DB_USER=viper
      - DB_PASSWORD=jP6=zZ4+hJ2_aD1-uM9+
      - DB_SSL=false

      - NEXT_PUBLIC_APP_URL=http://localhost:3000

      - R2_ACCESS_KEY_ID=f950fd678c608767ef973a91421097cc
      - R2_SECRET_ACCESS_KEY=5f6a85702d09715210c607aa6655e706e92b993588312c872a3ac2351d045e95
      - R2_ENDPOINT=https://f6d1d15e6f0b37b4b8fcad3c41a7922d.r2.cloudflarestorage.com
      - R2_BUCKET_NAME=apple-gold-anteater-it815

      - R2_PUBLIC_BASE=https://apple-gold-anteater-it815.sevalla.storage
      - NEXT_PUBLIC_R2_PUBLIC_BASE=https://apple-gold-anteater-it815.sevalla.storage
      - R2_PUBLIC_HOST=sevalla.storage
      - NEXT_PUBLIC_R2_PUBLIC_HOST=sevalla.storage

      - R2_SLIPS_ACCESS_KEY_ID=8dcebcd48001378ba37ef153393c5fce
      - R2_SLIPS_SECRET_ACCESS_KEY=dac9b7bb03714ffa41ebe9fe8ac3b464ad92e74b107d1be714a57a44c714acb4
      - R2_SLIPS_ENDPOINT=https://f6d1d15e6f0b37b4b8fcad3c41a7922d.r2.cloudflarestorage.com
      - R2_SLIPS_BUCKET_NAME=kiddycare-slips-738tn
      - R2_SLIPS_PUBLIC_BASE=https://kiddycare-slips-738tn.sevalla.storage
      - R2_SLIPS_PUBLIC_HOST=sevalla.storage
    networks:
      - cottonheart-network

networks:
  cottonheart-network:
    driver: bridge

